
disabled_rules:
  - line-length
  
opt_in_rules:
  - empty_count

included:
  - My WatchList
excluded:
  - Carthage
  - Pods
  - Sources/ExcludedFolder
  - Sources/ExcludedFile.swift
  - Sources/*/ExcludedFile.swift
